### ISSUE TITLE
Sync Products, Orders . . . to ERPNext

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#100]
Good Day

I am a newbie to Cezerin2 and looking for a online shop that can work good with ERPNext.
Could someone help to sync ERPNext products to Cezerin2 and Orders . . . 
ERPNext is a Open Source ERP Solution and would really like Cezerin2 and ERPNext to work together.

Thank You

Albertus Geyser

**Comment by ngoyal16** [comment]
you can create JS script... you can found sample in cezerin2-script repo

**Comment by albertusgeyser** [comment]
Good day

Thank You. 

I found this: https://github.com/fourzip/node-erpnext
that can help to make implementation easier, will try to do some dev as soon as i can get my test Cezerin2 server up and running.

**Comment by ngoyal16** [comment]
let me know if you need other help.
