### ISSUE TITLE
Tinymce do not show upload button for image and media

### ISSUE THREAD

**Issue by tronghuy2807** [Cezerin2/Server#101]
![Dashboard](https://user-images.githubusercontent.com/6357274/55546319-3d7da280-56f9-11e9-96ef-a58224655721.jpg)

**Comment by vamcart** [comment]
Interesting wysiwyg editor found.

https://editorjs.io

Maybe in future versions change TinyMCE to Editor.Js in cezerin. imho, editor.js is the best of the best.

**Comment by vamcart** [comment]
Upload button don't available because TinyMCE by default not include Image Manager plugin.

**Comment by tronghuy2807** [comment]
Thank you for your supporting

**Comment by vamcart** [comment]
@tronghuy2807 

Install image manager plugin for TinyMCE for this button availability.

For example, this image manager - https://github.com/trippo/ResponsiveFilemanager
