### ISSUE TITLE
Upload Logo in admin dashboard not working

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#102]
Good Day

If i upload an image (Logo) on admin dashboard then it shows blank.
Only could fix by manual idee by Andrei to load logo.png into /store/public/content/logo.png.

Hope this could be fixed.

Thank You

Albertus Geyser

**Comment by vamcart** [comment]
@ngoyal16 

Why you are assigning all issues for me?!

This bug as i see appeared after separation of cezerin and theme settings removing from monolith.

If you separate repos, make this work again.

Get back theme settings working at Admin - Settings - Theme.

With separated repos i have the same problem like issue starte with theme settings in admin.

**Comment by michaelrabelo** [comment]
For me it work's only if I set domain to http://localhost:3001 do you know why?

![Captura de Tela 2019-04-11 às 10 32 57](https://user-images.githubusercontent.com/4975044/55961487-5c25f100-5c45-11e9-9f18-2aa10e13c362.png)

**Comment by vamcart** [comment]
and the same problems with slider images upload at Admin - Settings - Theme.

**Comment by vamcart** [comment]
Fixed at #122
