### ISSUE TITLE
Mail send

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#103]
Good Day

Not sure if i do something wrong, but cannot send out mail with port 25 or 465.
If this works please provide gmail settings to test please.

**On Port 465**:

{"reason":"Host: domain.org.za. is not in the cert's altnames: DNS:srv38.hostserv.co.za, DNS:www.srv38.hostserv.co.za","host":"domain.org.za","cert":{"subject":{"OU":["Domain Control Validated","PositiveSSL"],"CN":"srv38.hostserv.co.za"},"issuer":{"C":"US","ST":"TX","L":"Houston","O":"cPanel, Inc.","CN":"cPanel, Inc. Certification Authority"},"subjectaltname":"DNS:srv38.hostserv.co.za, DNS:www.srv38.hostserv.co.za","infoAccess":{"CA Issuers - URI":["http://crt.comodoca.com/cPanelIncCertificationAuthority.crt"],"OCSP - URI":["http://ocsp.comodoca.com"]},"modulus":"","bits":2048,"exponent":"0x10001","pubkey":{"type":"Buffer","data"]},"valid_from":"Dec 25 00:00:00 2018 GMT","valid_to":"Dec 25 23:59:59 2019 GMT","fingerprint":"","fingerprint256":"","ext_key_usage":["1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"],"serialNumber":"","raw":{"type":"Buffer","data":]},"issuerCertificate":{"subject":{"C":"US","ST":"TX","L":"Houston","O":"cPanel, Inc.","CN":"cPanel, Inc. Certification Authority"},"issuer":{"C":"GB","ST":"Greater Manchester","L":"Salford","O":"COMODO CA Limited","CN":"COMODO RSA Certification Authority"},"infoAccess":{"CA Issuers - URI":["http://crt.comodoca.com/COMODORSAAddTrustCA.crt"],"OCSP - URI":["http://ocsp.comodoca.com"]},"modulus":"]},"valid_from":"May 18 00:00:00 2015 GMT","valid_to":"May 17 23:59:59 2025 GMT","fingerprint":"76:4D:2F:A5:9E:D1:23:F9:C9:55:70:C4:03:C9:2F:EF:33:8E:A7:45","fingerprint256":"","ext_key_usage":["1.3.6.1.5.5.7.3.1","1.3.6.1.5.5.7.3.2"],"serialNumber":"","raw":{"type":"Buffer","data":]},"issuerCertificate":{"subject":{"C":"GB","ST":"Greater Manchester","L":"Salford","O":"COMODO CA Limited","CN":"COMODO RSA Certification Authority"},"issuer":{"C":"SE","O":"AddTrust AB","OU":"AddTrust External TTP Network","CN":"AddTrust External CA Root"},"infoAccess":{"OCSP - URI":["http://ocsp.usertrust.com"]},"modulus":"]},"valid_from":"May 30 10:48:38 2000 GMT","valid_to":"May 30 10:48:38 2020 GMT","fingerprint":"]},"issuerCertificate":{"subject":{"C":"SE","O":"AddTrust AB","OU":"AddTrust External TTP Network","CN":"AddTrust External CA Root"},"issuer":{"C":"SE","O":"AddTrust AB","OU":"AddTrust External TTP Network","CN":"AddTrust External CA Root"},"modulus":"","bits":2048,"exponent":"0x10001","pubkey":{"type":"Buffer","data"},"issuerCertificate":"[Circular]"}}}},"code":"ECONNECTION","command":"CONN","level":"error","message":"Email send failedHostname/IP does not match certificate's altnames: Host: mail.lintel.org.za. is not in the cert's altnames: DNS:srv38.hostserv.co.za, DNS:www.srv38.hostserv.co.za","stack":"Error [ERR_TLS_CERT_ALTNAME_INVALID]: Hostname/IP does not match certificate's altnames: Host: mail.lintel.org.za. is not in the cert's altnames: DNS:srv38.hostserv.co.za, DNS:www.srv38.hostserv.co.za\n    at Object.checkServerIdentity (tls.js:245:12)\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1187:27)\n    at TLSSocket.emit (events.js:193:13)\n    at TLSSocket.EventEmitter.emit (domain.js:481:20)\n    at TLSSocket._finishInit (_tls_wrap.js:668:8)"}

**On Port 25:**

{"errno":"EHOSTUNREACH","code":"ECONNECTION","syscall":"connect","address":"1.1.1.1","port":25,"command":"CONN","level":"error","message":"Email send failedconnect EHOSTUNREACH 1.1.1.1:25","stack":"Error: connect EHOSTUNREACH 1.1.1.1:25\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)"}

Thank You

Albertus Geyser

**Comment by vamcart** [comment]
Try to add this string at the top of /config/server.js file:

process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";﻿

**Comment by vamcart** [comment]
and:
rejectUnhauthorized: false,

to the smtp server settings at /config/server.js

**Comment by albertusgeyser** [comment]
Thank You @vamcart this helped and worked.

**Comment by vamcart** [comment]
You're welcome.

**Comment by albertusgeyser** [comment]
https://stackoverflow.com/questions/31861109/tls-what-exactly-does-rejectunauthorized-mean-for-me
