### ISSUE TITLE
Instant Chat Widget Feature Request

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#108]
Good Day

Could we add a Instant Chat Widget to Cezerin2 for Customers to ask instant questions to Sales or Technical people?

I saw this:

https://github.com/kingofthestack/react-chat-window

Thank You

Albertus Geyser

**Comment by LuBuss** [comment]
have you looked at Facebook Customer Chat in Apps

**Comment by albertusgeyser** [comment]
I did, but do not see anything when enabling it. if you could guide me?
