### ISSUE TITLE
How to change language on the store?

### ISSUE THREAD

**Issue by IvanLjubicic** [Cezerin2/Server#11]
Hi guys,

first of all, thank you for continuing this great project.

I am not sure how to change language on the store, to be precise, how to use locales. I've changed config files to use different language, but only search bar is changed. Homepage remains in English.
Readme file lacks the proper explanation about this feature.

Thanks.

**Comment by LuBuss** [comment]
Hey IvanLjubicic,

The locales only change the fixed store elements, (Nav bar, Search Bar, Form Titles, etc.) 
The pages and products will not change language, these are fixed what has been loaded and added into the system. Though you can manually change these from the admin panel.

Please note, that not all languages are completely translated, And any help completing translations would be greatly appreciated.

Hope this helps.

**Comment by IvanLjubicic** [comment]
@LuBuss thanks.

What about the footer options ("Terms of service", "Privacy Policy", "Shipping & returns" etc.)? Or for example label home_products_title "BEST SELLERS"?
These are not translated to? Cause I see the translations in theme/settings folder, but it seems to me that these files aren't used. Or I am skipping something? What is the procedure to translate that?

I am planning to make translations on the Croatian language.

Thank you once again.

**Comment by LuBuss** [comment]
The footer definitions are defined in the setting -> Theme -> Footer. 
"BEST SELLERS" are defined in -> setting -> Theme -> Home. 
These would all be stored in your database. (The database setup is currently only available in English)

The Locales folder in cezerin2 defines all the translatable words, and if there is something missing from there, It means you would be able to customise the language from another location.
