### ISSUE TITLE
Tax Included and Rate

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#111]
Good Day

On settings i can not save Tax Included and Tax Rate.

![cezerin2_tax1](https://user-images.githubusercontent.com/31254389/55680660-c9bbdf80-591c-11e9-86b8-4c2e56a0b105.JPG)

I had a look at GET /api/v1/Settings and saw that there is no tax values.

![cezerin_tax2](https://user-images.githubusercontent.com/31254389/55680677-fff95f00-591c-11e9-87bc-db09df9ac3d8.jpg)

Thank You

Albertus Geyser

**Comment by LuBuss** [comment]
There is merge conflicts on tax pull request.

https://github.com/Cezerin2/cezerin2/pull/36

**Comment by albertusgeyser** [comment]
Thank You
Difficult to fix?

**Comment by LuBuss** [comment]
#141 Add Tax Settings
