### ISSUE TITLE
Product images on admin dashboard

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#112]
Good Day

Product images on admin dashboard not showing:

![cezerin_product_img](https://user-images.githubusercontent.com/31254389/55683205-87ef6100-593d-11e9-88cb-12eb3f335f87.jpg)

Thank You
Albertus Geyser

**Comment by LuBuss** [comment]
[Fixed](https://github.com/Cezerin2/cezerin2-admin/commit/3fdcf6dd0faaef67decbd2bb00c58de801a52a5b)
