### ISSUE TITLE
No Order Button on Back Order

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#119]
Good Day

Should product that allow back order not have order button?

![cezerin_backorder1](https://user-images.githubusercontent.com/31254389/55755199-b577ff80-5a4e-11e9-8b85-5f345d9fdc3e.JPG)

![cezerin_backorder2](https://user-images.githubusercontent.com/31254389/55755238-c9236600-5a4e-11e9-9440-36364c8a2df2.JPG)

Thank You
Albertus Geyser

**Comment by LuBuss** [comment]
I feel that they should, But this is not the current implementation.
