### ISSUE TITLE
Store ID / Multiple Stores Feature Request

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#124]
Good Day

1.) Would it be possibe to add a store_id in config file of cezerin2-store?
2.) In MongoDB database add store_id
3.) In cezerin2-admin - products add list to add stores where product must being added.

Multiple Stores with a central control over all incoming orders and payments.

Thank You

Albertus Geyser

**Comment by OmranAbazid** [comment]
I built a headless e-commerce application on top of Cezerin where I added users and multi-store functionality, You can find it here: https://github.com/OmranAbazid/Capi
