### ISSUE TITLE
Customer Login Portal Profile Spelling

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#127]
Good Day

Could someone help to fix spelling mistake of Profile in Customer Portal or help me to do my first change.

![cezerin_profile](https://user-images.githubusercontent.com/31254389/56088789-d5148b00-5e87-11e9-8795-3343c1d1eeef.JPG)

Thank You
Albertus Geyser

**Comment by vamcart** [comment]
Fixed - https://github.com/Cezerin2/cezerin2-store/commit/745fe61ddf743ce728ab4eac7105f2b445c15c50

This texts located at theme local files /cezerin2-store/theme/locales
