### ISSUE TITLE
Customer Portal Order Details

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#128]
Good Day

Is there any way to select columns to show on Order Details?

![Cezerin_Order_Details](https://user-images.githubusercontent.com/31254389/56088862-5f112380-5e89-11e9-982c-d24bd8b50344.JPG)

Thank You

Albertus Geyser

**Comment by vamcart** [comment]
Hi!

Why you are asking the questions in the issues?!
We have slack #cezerin2 channel.

It's not an issue, imho.
