### ISSUE TITLE
Shipping integration

### ISSUE THREAD

**Issue by jackyq2015** [Cezerin2/Server#129]
Is there any "Shipping Integration" feature to add custom shipping method ? if no, is there any plan to add it?

**Comment by albertusgeyser** [comment]
Good Day @jackyq2015 

Could you explain if you need an API or to add extra shipping method in Admin Dashboard?

Thank You
Albertus Geyser

**Comment by jackyq2015** [comment]
@Albertus Thanks for the quick response.
I want to add extra shipping method. But I assume the API(including getting the rate, posting the request and processing the response etc) should be in place before adding new shipping method.

**Comment by albertusgeyser** [comment]
Good Day @jackyq2015 

I think i saw what you mean.
When you add Shipping method with api then it will create a method, but everything will be blank?

![shipping_method](https://user-images.githubusercontent.com/31254389/56458381-27711280-6386-11e9-94f5-e472d1298a00.JPG)
