### ISSUE TITLE
Customer Order History

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#130]
Good Day

Could Order History being changed to show:
1] Order Number instead of Order ID.
2] Move SKU to Product Id Location.

Reason for this not to show values running over each other like on image:

![Cezerin_Order_History](https://user-images.githubusercontent.com/31254389/56454549-dd226e00-6352-11e9-9903-321080bd5cee.JPG)

Or could someone tell me which files i can edit to change?

Thank You
Albertus Geyser

**Comment by vamcart** [comment]
This is not looks like error, issue.
Add your question at our cezerin slack chat

https://join.slack.com/t/cezerin2/shared_invite/enQtNTE5NzYxMzA5ODc5LTVkZjM4ODUwMmNlMmMyZTkxYjg5N2QxZmQ5NjA1NTg3OWM2ZjU1NzVmNWM0N2E3ZmJjM2Q3MjQ5OGFmNTBmYjg

**Comment by albertusgeyser** [comment]
@vamcart if this not a problem, why order id and product id printing over each other?
Does this look professional?
If it looks good for you then it is probably because you don't really care about cezerin?

This for me is a bug . . .  for me the values should be replaced by  order number and sku. 
a customer does not want to see a order id and product id that is long and have no use for reference.

Thank You

Albertus Geyser

**Comment by ngoyal16** [comment]
will discuss what we can do for this.

**Comment by albertusgeyser** [comment]
Good Day

Ravi changed account.js for me to show order number instead of order id.

File Location: cezerin2-store/theme/src/components/account


[account.zip](https://github.com/Cezerin2/cezerin2/files/3102658/account.zip)

It shows like this with change:

![cezerin_ravi_account](https://user-images.githubusercontent.com/31254389/56490405-69fd3100-64e5-11e9-927f-9f6525701e20.JPG)

Thank You
Albertus Geyser

**Comment by vamcart** [comment]
Merged to the current code. Thanks!
