### ISSUE TITLE
Attributes Quantity - Feature Request

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#133]
Good Day

Could a Attribute Quantity being added next to Attributes as per image below:

![Cezerin_Attributes](https://user-images.githubusercontent.com/31254389/56463529-8494b480-63d6-11e9-92f8-78b0f5c71e8f.JPG)

Thank You
Albertus Geyser

**Comment by albertusgeyser** [comment]
Thank you **Ravi** for this easy, but nice looking change.

cezerin2-store\theme\src\components\productFilter\attributeFilter.js
line no 51
**{valueName} ({count})**

This is changed screen:

![cezerin_ravi_change](https://user-images.githubusercontent.com/31254389/56603843-d6b91e00-6600-11e9-91de-221adbff56f3.JPG)

**Comment by ngoyal16** [comment]
this pr is given to the repo or not

**Comment by albertusgeyser** [comment]
Yes, as i cannot yet give to project i will post it like this.

**Comment by ngoyal16** [comment]
didn't get you

**Comment by albertusgeyser** [comment]
no did not add to pull request as i do not know how to yet :(
i change to my code as i go.
if someone could guide me or take code as i post it to issues and add it to pr then would be great.

**Comment by ngoyal16** [comment]
you can fork the cezerin2-store after that you can change code in your githab fork
after that i will take care of it

**Comment by albertusgeyser** [comment]
https://github.com/Cezerin2/cezerin2-store/pull/22

**Comment by ngoyal16** [comment]
thanx will merge as soon as other reviews this

**Comment by vamcart** [comment]
Added to the master code.
