### ISSUE TITLE
Wishlist - Feature Request

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#135]
Good Day

Add wishlist to cezerin something similer to image below to click on heart or button.

![cezerin_wishlist](https://user-images.githubusercontent.com/31254389/56463819-ec013300-63db-11e9-95c2-5cf5e9908411.jpg)

Thank You
Albertus Geyser

**Comment by MarcoVdE** [comment]
Hi, 

busy going through open issues, it breaks the theme having the wish list icon there. Most stores would have it on the individual product page as a customer would check out a project before saying they want it; it would very rarely be a mass like action.
