### ISSUE TITLE
cannot register from the store

### ISSUE THREAD

**Issue by jackyq2015** [Cezerin2/Server#137]
After registration(password 1234), from the API server console:
info: Email sent {"accepted":["XXX@gmail.com"],"rejected":[],"response":"250 2.0.0 OK  1555813915 y11sm4336028ita.14 - gsmtp","envelope":{"from":"ZZZ@gmail.com","to":["XXX@gmail.com"]},"messageId":"f9e9d30e-bc12-09ed-f19e-99a24fc5d69d@gmail.com"}

From the firefox developer javascript console, there is no error. The email was received but it is empty body thus I have no way to active it.

**Comment by ngoyal16** [comment]
can you attach screen of the mail

**Comment by jackyq2015** [comment]
Please see below. It is from gmail web client:
![image](https://user-images.githubusercontent.com/10520203/56464858-0a593580-63c0-11e9-92d5-14e2a0e44bb3.png)

The source of it(body part):
Received: from [127.0.0.1] ([198.52.189.153])
        by smtp.gmail.com with ESMTPSA id l8sm3210111iob.39.2019.04.20.19.31.03
        for <XXX@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Sat, 20 Apr 2019 19:31:03 -0700 (PDT)
Content-Type: text/plain
From: cezerin2-admin <ZZZ@gmail.com>
To: XXX@gmail.com
Subject: Cezerin
Message-ID: <81863692-4e03-2c68-4574-94f7f073827e@gmail.com>
Date: Sun, 21 Apr 2019 02:31:00 +0000
MIME-Version: 1.0

**Comment by albertusgeyser** [comment]
@jackyq2015  please provide mail settings you use?

**Comment by vamcart** [comment]
Do you setup your database default data with "npm run setup" command?!

**Comment by vamcart** [comment]
Looks like you don't have email template for activation email.
Check Admin - Settings - Email

**Comment by jackyq2015** [comment]
I found the problem below:
$ echo $LANGUAGE
en_CA:en

As a workaround, I hard coded the config/server.js from:
// store UI language
`language: process.env.LANGUAGE || 'en',`
to:
`language:  'en',`

I know it is ugly. but at least it works. I think some enhancement is needed to extract the real language(en) from the $LANGUAGE

**Comment by vamcart** [comment]
Yes, you're right. I have the same problem. At my local machine with default config i have en_US default language and i've modify config to language: 'en' and it's work for me too.
