### ISSUE TITLE
Sorting by Date_Created and Date_Updated Not working  ** BUG **

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#139]
Good Day

After a long search i found reason for not sorting by Newest.
Standard Fields:

category_id	5cc5e28db652d81392b5d566
fields	path,id,name,category_id,category_name,sku,images,enabled,discontinued,stock_status,stock_quantity,price,on_sale,regular_price,attributes,tags,position
limit	30
offset	0
on_sale	
price_from	0
price_to	0
search	
sort	-date_created

But on fields to work the following should be fields:

fields :   path,id,name,category_id,category_name,sku,images,enabled,discontinued,stock_status,stock_quantity,price,on_sale,regular_price,attributes,tags,position,**date_created,date_updated**

These should be added for sorting: **date_created,date_updated**

Without date_created and date_updated test2 that is new should be on top (first), but is second.

![Cezerin_sort_X1](https://user-images.githubusercontent.com/31254389/56920571-d8348b80-6ac3-11e9-9510-fe2080fba070.JPG)

But with date_created and date_updated the test2 is on top as it is newest product added.

![Cezerin_sort_X2](https://user-images.githubusercontent.com/31254389/56920595-eda9b580-6ac3-11e9-9405-28e7797b0086.JPG)

Hope someone could help to fix Issue.

Thank You

Albertus Geyser

**Comment by albertusgeyser** [comment]
Good Day

Fix problem by adding date_created and date_updated to product fields:

![Cezerin_DateFix](https://user-images.githubusercontent.com/31254389/56921581-6c9fed80-6ac6-11e9-9170-b3f0c35d0275.JPG)

Should these fields be added by default in future?

Thank You

Albertus Geyser

**Comment by ngoyal16** [comment]
Give a PR if you feel that it helps
