### ISSUE TITLE
Show Logged In User Name - Feature Request

### ISSUE THREAD

**Issue by albertusgeyser** [Cezerin2/Server#143]
Good Day

Would it be possible to add logged in username somewhere on page?
The following a example of what it could look like:

![Cezerin_Welcome](https://user-images.githubusercontent.com/31254389/57587997-fe1f4e80-750d-11e9-84b4-5471d549d23c.JPG)

Thank You
Albertus Geyser

**Comment by chrisrijos** [comment]
Is the goal to display the current logged in customer here? Or add a customer page as well where they can see/edit data as well.

**Comment by albertusgeyser** [comment]
The idea is to show the current logged in user. There is already a customer settings page.

**Comment by franciscomolina** [comment]
Hi", did you solve this issue?

**Comment by albertusgeyser** [comment]
No not yet.

**Comment by LuBuss** [comment]
There is no one scheduled for this task in near future. Will require someone outside the regular developer to work on getting this complete

**Comment by vamcart** [comment]
This feature request completed. Thanks @chrisrijos Here is the Pull Request with the code from @chrisrijos 
https://github.com/Cezerin2/cezerin2-store/pull/29
And there is the screen how it's looks like.
![Screenshot from 2019-06-17 23-19-56](https://user-images.githubusercontent.com/3618501/59634371-4e19b280-9157-11e9-8b3c-e895866a184c.png)
