### ISSUE TITLE
Log from console does not appear

### ISSUE THREAD

**Issue by khaizanbaihaque** [Cezerin2/Server#149]
I try to display the log on the console with create-react-app with the console.log command as usual and it works, but how do I display logs in the console in this application?
I've been browsing but it hasn't been successful, is the console log in PWA and SPA different? Please help.

**Comment by LuBuss** [comment]
If your using pm2, you can go `pm2 logs`

**Comment by khaizanbaihaque** [comment]
The result is:
```
0|store    | info: Store running at http://localhost:3000
0|store    | info: Store running at http://localhost:3000
0|store    | info: Store running at http://localhost:3000
0|store    | info: Store running at http://localhost:3000
0|store    | info: Store running at http://localhost:3000
0|store    | info: Store running at http://localhost:3000
0|store    | info: Store running at http://localhost:3000
```

how if I display the API log request results to the console?

**Comment by LuBuss** [comment]
`pm2 logs api` if the name is still the same from setup

**Comment by khaizanbaihaque** [comment]
sorry, I mean log in the console browser is not in the terminal

like this:
![Screen Shot 2019-05-20 at 12 18 27](https://user-images.githubusercontent.com/26237057/57998135-5819a880-7afa-11e9-85dc-010b1270d84f.png)

**Comment by LuBuss** [comment]
Your building in production `npm run build` or development `npm run build:watch`

**Comment by khaizanbaihaque** [comment]
Wow.. thanks
