### ISSUE TITLE
Customer Login

### ISSUE THREAD

**Issue by LuBuss** [Cezerin2/Server#15]
migrate and refactor customer login from https://bitbucket.org/vajdamedia/vcommerce/src/master/

**Comment by thienpow** [comment]
i saw bitbucket has multiple updates... will it be merged here? or should i follow the bitbucket version.

**Comment by neunygph** [comment]
Hi @LuBuss , so the customer login feature is already merged into the main branch ?

**Comment by LuBuss** [comment]
This is currently not in Cezerin2, just waiting for @lortschi to finalize it.

**Comment by neunygph** [comment]
Oh I thought it’s from Lorant

**Comment by vamcart** [comment]
Merged to the master in PR #64
