### ISSUE TITLE
no such file or directory en_CA:en.json

### ISSUE THREAD

**Issue by EvanGee** [Cezerin2/Server#158]
first off, love the project so far, you guys are pretty awesome.

**Describe the bug**
I'm running this on chrome in Canada, I got this error when building and running 
ENOENT: no such file or directory, open 'cezerin2-admin/locales/en_CA:en.json'

**To Reproduce**
1. cd into cezerin2-admin/
2. npm run build

**To Solve**
I copied "en_US.json" and renamed it to "en_CA:en.json" in all the locals files (because Canada and the US are practically the same, save for we use metric units). I understand that I need a localised file unique to Canada, but is that naming convention normal? "en_CA:en.json?"

not sure if this is a bug or I just don't know your guy's app yet :)

loving the app so far.

**Comment by LuBuss** [comment]
Copy and rename to `en_CA.json`, please create pull requests for these

**Comment by EvanGee** [comment]
Hey thanks for the reply, I'm not sure I was clear about what the bug is. The bug is the colon after en_CA The error reads that is is missing en_CA:en.json, Not en_CA.json. When we name it like the rest of the 'locals' 'npm run build' fails.

Thanks.

**Comment by LuBuss** [comment]
@EvanGee Sorry for the delay, I will investigate this today.

**Comment by LuBuss** [comment]
I am not experiencing any problems creating a new locale en_CA. Have done this and everything is working as expected. The second point is that metrics are an admin setting, so this can be changed at any time and is not locked into any language.
