### ISSUE TITLE
stripe payement fails 

### ISSUE THREAD

**Issue by cioranique** [Cezerin2/Server#161]
i got this error on chrome dev tools while submiting payement through stripe 
 
ajax/cart/charge  :1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by LuBuss** [comment]
- Have you tested your stripe?
- have you had any payments processed by stripe before?
- This shows an error on the API, do you have the logs from api?

**Comment by cioranique** [comment]
no, but i've just found that in order for stripe to work it must run through Https:// while i'm still testing on and haven't bought a domain name yet so i don't know if there's an error in the api since it gives that error or as i said there must be https... have it worked for you my friend?

**Comment by LuBuss** [comment]
You can setup a Dev environment for stripe that I believe works under http://. But I always recommend making a purchase on implementation just to verify once deployed

I had received a Stripe plan just last week, so no problems once implement.

You will notice the API logs will provide more details on error. If your using pm2 just run `pm2 logs api`
