### ISSUE TITLE
Implement Google Spreadsheet product import

### ISSUE THREAD

**Issue by lortschi** [Cezerin2/Server#164]
**Current state:**
Products have to be setup manually.

**Should state:**
Products upload automatically from some source. E.q.: Google Spreadsheet

**Comment by golubev-n** [comment]
Can you describe in more detail how it works? I tried to export the product, filled in the api key, spreadsheet id, sheet name fields, but nothing happens.

**Comment by lortschi** [comment]
@golubev-n I have extended the docs: https://github.com/Cezerin2/cezerin2/blob/master/docs/api/product-import.md
