### ISSUE TITLE
I will try to translate it again

### ISSUE THREAD

**Issue by channingbox** [Cezerin2/Server#169]
Is it four places need to translate？

//Cezerin2/cezerin2-store/locales

//Cezerin2/Cezerin2-admin/locales

//Cezerin2/cezerin2/theme/settings

//Cezerin2/cezerin2-store/theme/settings

**Comment by LuBuss** [comment]
I believe cezerin2-store/theme/settings is no longer required or is a copy of cezerin2/theme/settings

**Comment by channingbox** [comment]
Ok，I see，thank u.
