### ISSUE TITLE
Code Debugging

### ISSUE THREAD

**Issue by DaniloCaruso** [Cezerin2/Server#174]
There is someone of good heart that can help me debug cezerin2-admin/store original code and not the compiled one from the ./dist?
(Help on debug server side is appreciate too :) )
Maybe from chrome developer tools or directly into vscode.
I'm really bad in configurations and i need some help.

Thnx alot guys. 👍

**Comment by lefcf** [comment]
Hi,
I think you can try
1. add
devtool: 'source-map',
into
cezerin2-store\webpack.config.store.js
2. insert 
debugger;
somewhere into code
3. run
npm run build:watch
4. run store
npm start
5. open
http://localhost:3000
6. open dev-tools
7. refresh page
