### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by zer0-um** [Cezerin2/Server#183]
Could a `Typescript` branch be created in order for pull requesting changes? We are a team of 2 interested in converting Cezerin2 into Typescript.

Cheers!

**Comment by vamcart** [comment]
Hi!

Thank you.
Typescript branches created at:

cezerin2/cezerin2
cezerin2/cezerin2-store
cezerin2/cezerin2-admin
cezerin2/cezerin2-client

**Comment by leonidkuznetsov18** [comment]
dont see these braches

**Comment by vamcart** [comment]
Branches tab at https://github.com/Cezerin2/cezerin2
