### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by EddieOne** [Cezerin2/Server#189]
**Describe the bug**
No demo. Maybe heroku would work?

**Comment by vamcart** [comment]
Here is online demo for cezerin:
https://demo.cezerin.net
https://admin.cezerin.net

**Comment by EddieOne** [comment]
Oh, it requires Nginix? That would say a lot about design choices.

The reason I was searching for Nodejs eCommerce was full stack Node is amazing when possible.

I'm not sure, if you want to manage that much. There is a module in Node which has replaced Nginx. https://github.com/http-party/node-http-proxy

**Comment by vamcart** [comment]
Yes, you need nginx to proxy web requests from site to api, store, dashboard apps.
Here is the docs - https://cezerin.org/docs
How to deploy cezerin on the web.
How to install cezerin.
How to install cezerin with docker, etc...

Cezerin 100% JS based. Frontend, backend. All based on JS. One language for all.

Thanks for the link. If this lib can replace nginx - it's awesome.

**Comment by vamcart** [comment]
We need to proxy all requests from web to our cezerin apps.

All requests from admin.domain.com proxy to localhost:3002 (running cezerin2-admin dashboard app)

All requests from domain.com proxy to localhost:3000 (running cezerin2-store frontend app)

All requests from domain.com/api, domain/ajax, domain/images proxy to localhost:3001 (running cezerin2 backend app)

Check nginx config for this proxy - https://raw.githubusercontent.com/Cezerin2/cezerin2/master/docs/nginx.md

**Comment by cioranique** [comment]
> We need to proxy all requests from web to our cezerin apps.
> 
> All requests from admin.domain.com proxy to localhost:3002 (running cezerin2-admin dashboard app)
> 
> All requests from domain.com proxy to localhost:3000 (running cezerin2-store frontend app)
> 
> All requests from domain.com/api, domain/ajax, domain/images proxy to localhost:3001 (running cezerin2 backend app)
> 
> Check nginx config for this proxy - https://raw.githubusercontent.com/Cezerin2/cezerin2/master/docs/nginx.md

how do you make image resizables by nginx?

**Comment by vamcart** [comment]
With nginx module image_filter and nginx config - https://raw.githubusercontent.com/Cezerin2/cezerin2/master/docs/nginx.md

Check https://cezerin.org/docs

**Comment by cioranique** [comment]
> With nginx module image_filter and nginx config - https://raw.githubusercontent.com/Cezerin2/cezerin2/master/docs/nginx.md
> 
> Check https://cezerin.org/docs

the module is installed by default when installing nginx-full , and i have the same nginx config from the docs but the images doesn't seem to be resized on the fly ... is there something wrong with server permissions or i should use S3 bucket? i use digitalocean

**Comment by vamcart** [comment]
By default all is working fine for me.
Thumbs created.

If you start cezerin2 on your local machine, of course thumbs is not working because you have npm web server, not nginx.

Nginx used when you deploy on the web and setup nginx - https://cezerin.org/docs/#/deploy-on-web-hosting

Or use docker installation.

Start with docker-compose, thumbs will be created - https://cezerin.org/docs/#/using-docker?id=docker-compose

**Comment by cioranique** [comment]
> By default all is working fine for me.
> Thumbs created.
> 
> If you start cezerin2 on your local machine, of course thumbs is not working because you have npm web server, not nginx.
> 
> Nginx used when you deploy on the web and setup nginx - https://cezerin.org/docs/#/deploy-on-web-hosting
> 
> Or use docker installation.
> 
> Start with docker-compose, thumbs will be created - https://cezerin.org/docs/#/using-docker?id=docker-compose

it's installed on the server not local, all is working fine except thumbs are not created in the cache directory, maybe because i browse the website by the ip adress  of the server not by domain name? because it;s still on development

**Comment by vamcart** [comment]
I don't know, what is your server settings
I have this nginx config - https://raw.githubusercontent.com/Cezerin2/cezerin2/master/docs/nginx.md
and thumb works for me on my domain.

**Comment by cioranique** [comment]
i have the same server config, https://raw.githubusercontent.com/Cezerin2/cezerin2/master/docs/nginx.md 

maybe they'll get resized when i add the domain, thanks anyway!

**Comment by vamcart** [comment]
Here is the working thumb sample - https://vamshop.ru/images/products/5dadd22796976428b790393c/100/box.png
