### ISSUE TITLE
Logo upload and slider images upload does not working at real installation with domain name (at local env all is fine, without real domain and ngnix)!

### ISSUE THREAD

**Issue by vamcart** [Cezerin2/Server#191]
Hey guys. I'm having trouble updating logo and slider images. Product images work fine however. Any help @Alex?

1 reply
1 day agoView thread
Alex 6:50 PM
Hi! Yes, we have problem with logo image and slider images. When you test it on localhost - all is fine. But when you install cezerin on the domain name, this problem is actual. (edited) 
Not updated from admin
URL of images is not correct. Image file uploaded to the /cezerin2/public/content/assets/images , but at storefront images trying to displat file from /cezerin2-store/theme/assets/images (edited) 
cinnaman 12:30 PM
Thanks @Alex I can confirm that copying images from API to Store after upload fixes this problem. Not sure which would be simpler to do: change upload location or location where storefront is displaying from :thinking_face:

**Comment by golubev-n** [comment]
I have a similar problem. I am using ubuntu 18.04 and nginx 1.14.0.
Image files are uploaded to the /cezerin2/public/content/assets/images, but taken from another folder /cezerin2-store/theme/assets/images. 

Uploading product images works fine. Pictures are uploaded to /cezerin2/public/content/images/products/same_hash/ and taken from there.

How to change the path for the logo image and slides to /cezerin2-store/theme/assets/ images? Maybe is there another way?

**Comment by vamcart** [comment]
Пока что не решена эта проблема.

**Comment by golubev-n** [comment]
И файлы темы он тоже выгружает не от туда, но это, видимо, можно поправить в scripts/theme-export.sh.

**Comment by vamcart** [comment]
Да, эти все проблемы вылези из-за разделения приложения на 3
api
storefront
admin

Раньше всё было единым приложением, как в оригианльном cezerin и таких проблем там нет.

Мы вот сделали единым приложением всё - https://github.com/Cezerin2/cezerin2-mono

Там этих проблем нет, по идее.

**Comment by golubev-n** [comment]
Да, на локалке вроде работает! Придется переделать все.

**Comment by vamcart** [comment]
Alexander VamShop, [01.04.20 17:35]
там есть глюк в cezerin2 со слайдами в настройках темы и файлом настроек темы

Alexander VamShop, [01.04.20 17:35]
слайды и настройки записываются в папку backend

Alexander VamShop, [01.04.20 17:36]
а конфиг ngnix грузит их из cezerin2-storefront

Alexander VamShop, [01.04.20 17:36]
Этот баг вылез после того как оригинальный cezerin был разделён на 3 отдельны приложения

Alexander VamShop, [01.04.20 17:36]
api, front и dashboard

Alexander VamShop, [01.04.20 17:37]
Я пока не знаю как исправить этот баг. Надо либо ngnix конфиг как-то переделывать, либо править storefront и backend изменяя пути к слайдам

Alexander VamShop, [01.04.20 17:37]
Этот же глюк есть и в модули Импорта даных из google sheets и в админке, в разделе Файлы.

Alexander VamShop, [01.04.20 17:35]
там есть глюк в cezerin2 со слайдами в настройках темы и файлом настроек темы

Alexander VamShop, [01.04.20 17:35]
слайды и настройки записываются в папку backend

Alexander VamShop, [01.04.20 17:36]
а конфиг ngnix грузит их из cezerin2-storefront

Alexander VamShop, [01.04.20 17:36]
Этот баг вылез после того как оригинальный cezerin был разделён на 3 отдельны приложения

Alexander VamShop, [01.04.20 17:36]
api, front и dashboard

Alexander VamShop, [01.04.20 17:37]
Я пока не знаю как исправить этот баг. Надо либо ngnix конфиг как-то переделывать, либо править storefront и backend изменяя пути к слайдам

Alexander VamShop, [01.04.20 17:37]
Этот же глюк есть и в модули Импорта даных из google sheets и в админке, в разделе Файлы.

Alexander VamShop, [01.04.20 17:37]
Это я так, на будущее, то, что я заметил, когда тестировал

Alexander VamShop, [01.04.20 17:38]
сохраняется в cezerin2 backeend приложение. А cezerin2-storefront берёт файлы из своей папки theme, в этом и глюк.

Alexander VamShop, [01.04.20 17:39]
Самое просто решение - можно просто на стороне файловой системы сделать символичкую ссылку на папку с backend на frontend

Alexander VamShop, [01.04.20 17:39]
но по хорошему надо раскопать конечно этот глюк и исправить, может чуть позже будет у меня время

Alexander VamShop, [01.04.20 17:35]
там есть глюк в cezerin2 со слайдами в настройках темы и файлом настроек темы

Alexander VamShop, [01.04.20 17:35]
слайды и настройки записываются в папку backend

Alexander VamShop, [01.04.20 17:36]
а конфиг ngnix грузит их из cezerin2-storefront

Alexander VamShop, [01.04.20 17:36]
Этот баг вылез после того как оригинальный cezerin был разделён на 3 отдельны приложения

Alexander VamShop, [01.04.20 17:36]
api, front и dashboard

Alexander VamShop, [01.04.20 17:37]
Я пока не знаю как исправить этот баг. Надо либо ngnix конфиг как-то переделывать, либо править storefront и backend изменяя пути к слайдам

Alexander VamShop, [01.04.20 17:37]
Этот же глюк есть и в модули Импорта даных из google sheets и в админке, в разделе Файлы.

Alexander VamShop, [01.04.20 17:37]
Это я так, на будущее, то, что я заметил, когда тестировал

Alexander VamShop, [01.04.20 17:38]
сохраняется в cezerin2 backeend приложение. А cezerin2-storefront берёт файлы из своей папки theme, в этом и глюк.

Alexander VamShop, [01.04.20 17:39]
Самое просто решение - можно просто на стороне файловой системы сделать символичкую ссылку на папку с backend на frontend

Alexander VamShop, [01.04.20 17:39]
но по хорошему надо раскопать конечно этот глюк и исправить, может чуть позже будет у меня время

Alexander VamShop, [01.04.20 17:40]
есть в issue

Alexander VamShop, [01.04.20 17:40]
сейчас скину ссылку

Alexander VamShop, [01.04.20 17:40]
в общем, костыль такой

Alexander VamShop, [01.04.20 17:41]
cezertin2-storefront/theme/settings папка должна быть ссылкой в cezerin2/theme/settings

Alexander VamShop, [01.04.20 17:42]
cezerin2-storefront/theme/assets/images должна быть ссылкой в /cezerin2/public/content/assets/images

Alexander VamShop, [01.04.20 17:43]
но это конечно порнуха, по-хорошему надо сделать нормально, что б настройки темы и слайды сохраняли в папку backend, а cezerin2-store брать слайды и настройки именно из backend

Alexander VamShop, [01.04.20 17:43]
Причём этот глюк на льканом компе никак не виден

Alexander VamShop, [01.04.20 17:43]
Когда всё рабоатет на localhost

Alexander VamShop, [01.04.20 17:43]
Всё хорошо

Alexander VamShop, [01.04.20 17:43]
Проблема когда настраиваешь ngnix и запускаешь на домене

И вот строка в ngnix конфиге - https://raw.githubusercontent.com/Cezerin2/cezerin2/master/docs/nginx.md

Вот эта строка:

        location /assets/ {
                alias /var/www/cezerin2-store/theme/assets/;

т.е. берёт из cezerin2-store файлы, а когда правишь настройки темы в админке, то backend записывает настройки и слайды в свою backend папку.
