### ISSUE TITLE
Add to cart is not working on Demo Store

### ISSUE THREAD

**Issue by ghost** [Cezerin2/Server#201]
**The bug**
Add to cart is not working on Demo Store

**To Reproduce**
Here what happened:
1. The first time I visit the demo store its working fine.
2. But now (not the first time anymore) when I clicked the add to cart, it not working anymore.
3. But when I open it in Incognito mode, try it, and its works!

**Expected behavior**
normal behavior is when we click add to cart, the product will be added to the cart.

**Screenshots**
its not working:
![1](https://user-images.githubusercontent.com/57020051/73599522-05442c00-4577-11ea-8734-4d3ffdcc64b9.png)
in Incognito:
![2](https://user-images.githubusercontent.com/57020051/73599525-0b3a0d00-4577-11ea-8887-47643b5e02d5.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Chrome
 - Version 79.0.3945.130

**Comment by vamcart** [comment]
Can't reproduce at my chrome.
Works fine for me.

**Comment by ghost** [comment]
yup, after I read your comment, when I try it few moment ago, its work fine.
idk why its not working before, you know I really can't add that product to my cart, but now its working fine. thanks.
