### ISSUE TITLE
Nginx 

### ISSUE THREAD

**Issue by saugatpahari** [Cezerin2/Server#204]
I do have a CentOS Linux release 7.1 as my OS where i donot find any sites-available so where should i have the changes if i do the changes in nginx.conf it gives an error saying -  ""server" directive is not allowed here in /etc/nginx/nginx.conf:1"

**Comment by vamcart** [comment]
Check this config - https://cezerin.org/docs/#/deploy-on-web-nginx
I have ubuntu with that nginx config. Works fine.
