### ISSUE TITLE
WebSocket connection to 'wss://ktmkart.com/ws/dashboard?token=null' failed: Error during WebSocket handshake: Unexpected response code: 502

### ISSUE THREAD

**Issue by saugatpahari** [Cezerin2/Server#205]
I am getting this error after hosting the site live 
![image](https://user-images.githubusercontent.com/42732216/77909664-779e6780-72ad-11ea-833e-d8c52f4f33a7.png)

**Comment by jackyq2015** [comment]
How did you install it? I found there are several documents regarding how to install which may cause confusing. 

For me, this works:
https://github.com/cezerin2/cezerin2/blob/master/docs/using-source-code.md

But this fails:
https://github.com/Cezerin2/cezerin2/blob/3675ec4c1b2adb4b5e263722eeeb1aa8b160bff2/docs/how-to-deploy-a-cezerin2-on-ubuntu-18-04-1-github.md

Seems the  https://github.com/Cezerin2/cezerin2/ repo contains all the components(API, store and admin) but the installation doc has some issue(Or the separated repos have the updated code). Not quite sure. @vamcart ?

**Comment by vamcart** [comment]
@jackyq2015 

https://github.com/Cezerin2/cezerin2/tree/master/docs

Check now.

Docs cleaned and updated.

**Comment by jackyq2015** [comment]
@vamcart Cool. so it is supposed to build and run separately from  different repos. Then I think it is better to reflect the same on this repo by removing the code belongs to other components(store and admin). It is good to always keep the single root of the truth.

**Comment by vamcart** [comment]
ok, maybe in future, i don't have a free time for separated DOCS for every app at this moment.

By the way...
You can use mono repo - https://github.com/cezerin2/cezerin2-mono

All-in-one

Not separated
