### ISSUE TITLE
pm2  api respond

### ISSUE THREAD

**Issue by shsunmoonlee** [Cezerin2/Server#21]
pPM2][ERROR] script not found : /Users/seunghunlee/Clients/Seunghun/cezerin2/dist/store/server/index.js
[PM2] App [api] launched (1 instances)

**Comment by gergana95** [comment]
I had the same issue. I ran `npm run compile` and the admin, store and server folders were compiled and generated in the dist folder.

**Comment by LuBuss** [comment]
I look like either you have forgotten to run `npm run build` or an error has occurred during this process and has not completed. 

`npm run compile` is part of the `npm run build` process.

**Comment by shsunmoonlee** [comment]
you were right! thanks!
