### ISSUE TITLE
Add new product custom setting toggle in Product Edit Inventory

### ISSUE THREAD

**Issue by gergana95** [Cezerin2/Server#22]
I created a new store with cezerin about bookselling. I want to have a new variable property for each product that would be a toggle and should indicate whether the book is electronic or not. Similar to 'Enabled' and 'Discontinued' in Edit Product page.

Is there an approach documented somewhere that I can use and that is going to save the new property in the db and on the admin panel?

**Comment by LuBuss** [comment]
Have you thought of using attributes and variants to solve this problem

**Comment by gergana95** [comment]
I figured I could use the tag, but I think there should be documentation about how to add new fields in admin panel and use them.

**Comment by LuBuss** [comment]
Would be greatly appreciated if you can start the write-up from what you have learnt.

Do we want to keep the issue open or are you happy with you findings?
