### ISSUE TITLE
Basic Cookie Banner

### ISSUE THREAD

**Issue by lortschi** [Cezerin2/Server#230]
Basic Cookie Banner

Cookie Banner should be shown on all pages if it is set to visible in settings. The banner could be self adjusted in the dashboard of Cezerin2.

Now is no Cookie Banner set up in webshop and in production mode is against the general data protection regulation law.

**Comment by Himadu2000** [comment]
Is this issue is done or still work in progress?

**Comment by vamcart** [comment]
Done
