### ISSUE TITLE
change process.json, delete config/server.js => всё пропало ) 

### ISSUE THREAD

**Issue by LightDiver** [Cezerin2/Server#231]
В последних изменениях  смотрю что 
в process.json: 
'-'      "script": "./src/index.js",
'+'      "script": "./build/index.js",
'-'      "watch": ["./config/server.js", "./src/"],
'+'      "watch": ["./build/"],

однако каталога build не существует, а каталог config удален. 
В результате start не отрабатывает.

**Comment by vamcart** [comment]
Это переход на TypeScript.
Что б появился build, надо выполнить команду: npm run compile
В документации уже обновлено: https://cezerin.org/docs
Там будет куча ошибок, но это ничего страшного, со временем поправим, надеюсь. TypeScript просто более строгий в коду.
После npm run compile запускайте npm start
Всё будет работать.
