### ISSUE TITLE
npm run build error Module not found: Error: Can't resolve '../../../config/server'

### ISSUE THREAD

**Issue by shsunmoonlee** [Cezerin2/Server#29]
Hi, 
I appreciate your help!
I'm getting error when i run npm run build 
```
ERROR in ./node_modules/theme/dist/lib/apiClient.js
Module not found: Error: Can't resolve '../../../config/server' in '/Users/seunghunlee/Clients/Seunghun/cand
le-shop-v0.1/node_modules/theme/dist/lib'
 @ ./node_modules/theme/dist/lib/apiClient.js 3:0-52 60:11-25
 @ ./node_modules/theme/dist/components/signIn/index.js
 @ ./node_modules/theme/dist/containers/shared.js
 @ ./node_modules/theme/dist/index.js
 @ multi theme
```

**Comment by LuBuss** [comment]
@SeunghunSunmoonLee has this been resolved or do you still need some help with it.

**Comment by ngoyal16** [comment]
@SeunghunSunmoonLee you didn't create server.js file in config folder which is causing this problem..

cd cezerin/config
mv admin.production.js admin.js
mv store.production.js store.js
mv server.production.js server.js

you can run this command
