### ISSUE TITLE
move to schema model

### ISSUE THREAD

**Issue by madibalive** [Cezerin2/Server#34]
Hi i have started updating my local copy with features, would push when stable , but biggest issue i have is the cezerin original lack mongo db schema ?? is there is reason you guys are sticking to no schema model, i was wondering if you where open to schema modules, allows to switching out database , am currently using mysql with sequilize as orm, fairly straight forward , using global search for collection keyword and modifying each code to use the sequilize ?

**Comment by neunygph** [comment]
Why is it an issue for you, MongoDB is a schemaless database, it makes it flexible to update and add new fields.

**Comment by madibalive** [comment]
my issue is that most mongodb project i have worked on, or most opensourced project using mongodb tends to have a schema model which allows for hooks (before and after save,update,create ... ), 
was wondering if there is reason your guys sticking to no schema model, or would be entertain moving to a mongodb schema model?

**Comment by lfurzewaddock** [comment]
Consider postgreSQL. JSONB column datatype can be used when neccessary for migration from mongoDB.
