### ISSUE TITLE
want to move assets to S3 so that our main server don't get load

### ISSUE THREAD

**Issue by ngoyal16** [Cezerin2/Server#35]
want to move assets to S3 so that our main server doesn't get a high load of assets like product images.

**Comment by neunygph** [comment]
I can work on this

**Comment by ngoyal16** [comment]
@neunygph can you help me with it..

**Comment by neunygph** [comment]
I’m familiar with amazon but I’m still not familiar with this project architecture yet and I’m still new to React so I’m not planning to implement this anytime soon, sorry I wish I could help.

**Comment by ngoyal16** [comment]
I am setting up the things on the serverless system.. I am able to move APIs to serverless successfully but only image upload part is problem for now

**Comment by neunygph** [comment]
Did you separate the api from the project?

**Comment by ngoyal16** [comment]
Yes I did I will create new repo soon

**Comment by neunygph** [comment]
Can you show me how you separate them ?

Phuong Nguyen

On Jan 26, 2019, at 7:34 PM, Nitin Goyal <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes I did I will create new repo soon

**Comment by neunygph** [comment]
Can you show me how you separate them please?

**Comment by ngoyal16** [comment]
I am creating new repo today.. you can use that...
