### ISSUE TITLE
why not make system independent so that each bundle size get reduce..

### ISSUE THREAD

**Issue by ngoyal16** [Cezerin2/Server#38]
why not make the system independent so that each bundle size get reduce and easy to maintain...

1. admin interface
2. api code
3. store code

if you think that code is very integrated with each other then uses git submodule feature for common code.. this way.. each of the code gets separated.. and new members of this project can understand its function.

you can start this by moving out admin panel from the code... i can help you with that because last night I struggle with many problems to make them independent.

**Comment by ngoyal16** [comment]
it also helps peoples to make admin & store panel on separate domains which can help to protect their admin by firewalls too easily.

**Comment by LuBuss** [comment]
We have had this conversation before, I added a poll in the slack channel to try resolve if you will accept the changes or not. https://join.slack.com/t/cezerin2/shared_invite/enQtNTE5NzYxMzA5ODc5LTVkZjM4ODUwMmNlMmMyZTkxYjg5N2QxZmQ5NjA1NTg3OWM2ZjU1NzVmNWM0N2E3ZmJjM2Q3MjQ5OGFmNTBmYjg
