### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by rever96** [Cezerin2/Server#44]
Installing:
`git clone https://github.com/cezerin2/cezerin2.git cezerin` works!!
`cd cezerin` works xd
`npm install` works??
`npm run build` failed with error about theme import
`npm install theme --save` it solved the theme problem
`npm run build` failed like this: 

> ERROR in assets/js/app-03db75ae900df00e597f.js from Terser
> TypeError: Cannot read property 'minify' of undefined at minify (/home/loris/cezerin/node_modules/terser-webpack-plugin/dist/minify.js:175:23)

changed `_terser.default.minify` to `_terser.minify`
`npm run build` finally ended without errors

`npm start` works...
open other terminal and: `npm install pm2 -g`
`pm2 start process.json` makes "api" and "store" online
http://localhost:3000 this page works
http://localhost:3000/admin that page say not found
http://localhost:3001 cannot get

pls help!

**Comment by ngoyal16** [comment]
We have takeout the admin panel from cezerin2...

**Comment by ngoyal16** [comment]
We have to check theme problem.. can you let us know what configuration u have used..
