### ISSUE TITLE
PayPal handleSuccessPayment in checkoutForm/index.js

### ISSUE THREAD

**Issue by thienpow** [Cezerin2/Server#52]
handleSuccessPayment should not pass empty data at  checkout(null), if PayPal payment success, checkout function should carry values like the step in handleShippingSubmit...

**Comment by thienpow** [comment]
<img width="883" alt="screenshot 2019-02-14 at 1 20 31 am" src="https://user-images.githubusercontent.com/9796623/52753043-217e4e80-3030-11e9-9d61-e9aa85715485.png">

**Comment by Pfurr** [comment]
can you fix it?
