### ISSUE TITLE
Deploying on AWS EC2

### ISSUE THREAD

**Issue by alan-llin** [Cezerin2/Server#66]
I am currently have the original one deployed on my AWS EC2 Instance, but I am getting a connection refused error when the API is trying to make a call. The products would not show up if I click on the category tab, but if I click on it and then refresh it. It shows up with no issue. I think it is because of CORS. I am pretty sure Nginx would solve that issue, but I am not sure if the config file would work for AWS EC2 or just DigitalOcean.

**Comment by LuBuss** [comment]
Assuming origin is v0.33.0.

if the single domain you can set 
`STORE_URL=*` 
or set it to your domain name.

**Comment by alan-llin** [comment]
Where can I set the `STORE_URL`?
Heres the error that I get when I load onto my home page, everything displays except for the best sellers. The same type of error displays when I try to redirect.

`OPTIONS http://localhost:3001/ajax/products?category_id&fields=path%2Cid%2Cname%2Ccategory_id%2Ccategory_name%2Csku%2Cimages%2Cenabled%2Cdiscontinued%2Cstock_status%2Cstock_quantity%2Cprice%2Con_sale%2Cregular_price%2Cattributes%2Ctags&ids&limit=8&offset=0&on_sale&price_from&price_to&search&sku&sort=stock_quantity&tags net::ERR_CONNECTION_REFUSED`

**Comment by alan-llin** [comment]
Found the issue. All the urls in the config folder must be set to the domain you are using and not localhost.

**Comment by s3665959** [comment]
@alan-llin  i am having this problem ,  which file do i need to change from localhost to domain?
thank you

**Comment by omerfrkolcy** [comment]
@alan-llin  hey man, could you help us a little bit about this issue. do i need to use my machine's IP instead of localhost ? if so, which files do i have to change? and there are 4 containers for cezerin2 (mongodb, cezerin2, cezerin2-store, cezerin2-admin) which container do we need to change config files on?
