### ISSUE TITLE
Issue during installation

### ISSUE THREAD

**Issue by pablo-pietra** [Cezerin2/Server#67]
Hi everyone,
I have an issue while running npm install, it says:

Could not install from "theme" as it does not contain a package.json file.

I tried downloading and installing cezerin old version and it worked ok but with cezerin2 I'm getting this error message...

**Comment by vamcart** [comment]
Repos are separated to apps.
cezerin2 - backend app
cezerin2-store - frontend app
cezrein2-admin - dashboard

Run "npm install" from the app folder, not in the theme folder.

Clone (download) cezerin2-store and run "npm install" inside cezerin2-store folder, not in "cezerin2-store/theme".
