### ISSUE TITLE
Code customization

### ISSUE THREAD

**Issue by HenryHengZJ** [Cezerin2/Server#74]
Sorry for the stupid question.. But how can I customize codes like homepage slider, button, labels etc. I have seen the react files at theme/src, but when I modified the codes and run npm start again, it doesn't reflect any changes I've made.

**Comment by ngoyal16** [comment]
whenever you made changes to code either do a hot reload using web pack or build it again the run it

**Comment by vamcart** [comment]
You can edit homepage slider, links, logos in Admin - Settings - Theme.
