### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by LuisGVV** [Cezerin2/Server#75]
I'm just found out the project and want to contribute and develop features... However I noticed that there isn't a command for `npm test` nor any test files

Can someone tell me if the project currently has tests or where can I find them? This would help a lot around new people like me to the project or future contributors to navigate the codebase and ensure features don't break

**Comment by ngoyal16** [comment]
currently there are no test case but looking forward to contribute in it.

**Comment by LuBuss** [comment]
There is some tests under a pull request though these added a security vulnerability and required a db and so we are not merging. This maybe a good spot to start looking if you want to contribute

**Comment by LuisGVV** [comment]
Thanks for answering, looking forward for these.

Closing this issue
