### ISSUE TITLE
How to add custom functionality

### ISSUE THREAD

**Issue by mahaveer0496** [Cezerin2/Server#78]
Hey guys a client of mine needed an e-commerce JS solution and this is a wonderful project (judging from the demo). But, some custom functionality (Chat, Coupon) is to be added by me, and i can't even figure out how to setup the project for local development.

Can someone please help with
* Setup
* Code customization
* Some guideline on the best way to add new stuff without breaking the app as testing isn't implemented :)

Also, after i've added these custom features, i'll make sure to submit a PR :)

Thanks a lot :D

**Comment by ngoyal16** [comment]
hello @mahaveer0496  you can follow guides at our new doc. cezerin.org/docs to set up this on server or local.

**Comment by vamcart** [comment]
And here is the Pull Requests, for example, for customer feature:

https://github.com/Cezerin2/cezerin2-client/pull/7
https://github.com/Cezerin2/cezerin2/pull/64
https://github.com/Cezerin2/cezerin2-store/pull/7

**Comment by mahaveer0496** [comment]
the doc mentions nginx, can we not simply develop with Node on windows ? :(

**Comment by vamcart** [comment]
Of course you can.
nginx required for production mode with domain name, setup proxy for cezerin apps.

**Comment by mahaveer0496** [comment]
* npm install 
* npm start 
and i get this 
![image](https://user-images.githubusercontent.com/23198481/54305277-f8c88500-45ec-11e9-8cc8-8c6b653c8b61.png)
cant see app :(

Edit : I'm on windows 

Edit : `npm run setup` is giving error
![image](https://user-images.githubusercontent.com/23198481/54305627-b81d3b80-45ed-11e9-8e74-e21cdca899ad.png)

**Comment by mahaveer0496** [comment]
Also can someone please tell me whats the difference in Cezerin Installation and Cezerin Admin installation? 

Thanks :D

**Comment by vamcart** [comment]
Cezerin2 - backend (api) and do not require the build (npm run build). Just npm install && npm start
cezerin2-admin is require to be build.

npm install
npm run build

then run:

pm2 serve ./dist 3002

or:

pm2 start process.json

and admin will be available on http://localhost:3002 on your browser

**Comment by vamcart** [comment]
Here is the manual for cezerin installation process (+ youtube videos) - https://cezerin.org/docs/#/using-source-code
