### ISSUE TITLE
Fullname and address are absent in purchase order. Is it expected behavior?

### ISSUE THREAD

**Issue by DenisRozhko** [Cezerin2/Server#79]

**Comment by vamcart** [comment]
Как гость или как зарегистрированный покупатель оформляете заказ?!
У меня всё нормально, и адрес и имя видны.

**Comment by DenisRozhko** [comment]
> Как гость или как зарегистрированный покупатель оформляете заказ?!
> У меня всё нормально, и адрес и имя видны.

Я разобрался, просто очень странно что эти данные в доставке, а не данные о пользователе. Кстати разве можно зарегистрировать пользователя? или это надо где-то включить

**Comment by vamcart** [comment]
Можно, в текущем коде уже добавлена новая функциональность покупателя.

Вот здесь например справа срвеху - http://elpatron.21ninjas.es/

Можно видеть как это выглядит. Рядом с поиском.

т.е. в магазине можно регистирроваться, авторизоваться, есть личный кабинет с заказами, с редактированием адресов.
Напоминалка пароля есть, шаблоны писем регистрации, напоминалки.

Всё это добавлено в текущем коде.

В чате всё обсуждалось.

Заходите в чат на slack: https://join.slack.com/t/cezerin2/shared_invite/enQtNTE5NzYxMzA5ODc5LTVkZjM4ODUwMmNlMmMyZTkxYjg5N2QxZmQ5NjA1NTg3OWM2ZjU1NzVmNWM0N2E3ZmJjM2Q3MjQ5OGFmNTBmYjg

Я там создал комнату russian для русскоязычных пользователей.
