### ISSUE TITLE
Running all parts of project 

### ISSUE THREAD

**Issue by tomerBZ** [Cezerin2/Server#81]
Hi guys

Thank you so much for keeping this project alive!

After following all of your docs and trying every possible way to run the project as a whole (docker/git) it seems none of the docs are completed...

Am I missing something?

would love to have this working (was trying to make all the docker containers run together using compose and failed) [single-instance](https://github.com/Cezerin2/cezerin2/tree/master/docs/single-instance)

**Comment by vamcart** [comment]
Hi!

I have ubuntu (with installed mongodb) on my local machine and i make this to start cezerin2:

1. git clone https://github.com/Cezerin2/cezerin2.git

cd cezerin2
npm install
npm start

and your backend (api) available at http://localhost:3001

2. git clone https://github.com/Cezerin2/cezerin2-store.git

cd cezerin2-store
npm install
npm run build
npm start

and your frontend (store) available at http://localhost:3000

3. git clone https://github.com/Cezerin2/cezerin2-admin.git

cd cezerin2-admin
npm install
npm run build

pm2 start process.json

or:

pm2 server ./dist 3002

and your dashboard available at http://localhost:3002


That's all!

I'm using this manual every day while working on cezerin2 code on my ubuntu machine.

**Comment by vamcart** [comment]
Join us at slack channel - https://join.slack.com/t/cezerin2/shared_invite/enQtNTE5NzYxMzA5ODc5LTVkZjM4ODUwMmNlMmMyZTkxYjg5N2QxZmQ5NjA1NTg3OWM2ZjU1NzVmNWM0N2E3ZmJjM2Q3MjQ5OGFmNTBmYjg
