### ISSUE TITLE
How to generate JWT and Cookies 

### ISSUE THREAD

**Issue by ismoil-nosr** [Cezerin2/Server#95]
Ok, it's newbie again. Please, refer me to right place or help me with generating of tokens. I can't understand how to make them.
 And also another question: is it needed to use smtp? Because i dont know what credentials to use . Thanks for all of you.

P.S. sorry for my English

**Comment by vamcart** [comment]
You can run this command in your cezerin2 (backnd, api) folder:
npm run setup your@email.com http://your-domain.com

**Comment by ismoil-nosr** [comment]
@vamcart, thank you for your reply. This command will automatically generate those tokens, right?

**Comment by vamcart** [comment]
Yes, you can see new line added at Admin - Settings - Access tokens.

**Comment by ngoyal16** [comment]
he is talking about the jwt token and cookie secret ...

@izzy777  you can put any random string there

**Comment by ismoil-nosr** [comment]
@ngoyal16, thanks a lot. This is what i want to know. And also could you help me with installation, please? Because i'm doing as described in FAQ but without success. I'm deploying project in Amazon AWS EC2 instance and there are errors when i'm doing command "npm i" .

**Comment by ngoyal16** [comment]
what is the error you are getting?

**Comment by ismoil-nosr** [comment]
@ngoyal16 , Hi. I tried to install again and all worked. But when I type mydomain.com:3002 I'm getting in to dashboard without any login credentials. Also I cant add any products or change settings. What I have missed out while installing cezerin? I used [ this manual](https://github.com/Cezerin2/cezerin2/blob/master/docs/using-source-code.md) to install.

**Comment by vamcart** [comment]
Try this - https://github.com/Cezerin2/cezerin2/blob/master/docs/how-to-deploy-a-cezerin2-on-ubuntu-16-04.md#7-turn-off-developer-mode

**Comment by ismoil-nosr** [comment]
@vamcart thanks for your response. Could you guide me how to add access token to MongoDB? because it seems that dashboard not functional at all (I can only view dashboard, without making any changes)

**Comment by vamcart** [comment]
Check Chrome Developer console.
What the errors at your admin dashboard.
