### ISSUE TITLE
Admin Routes

### ISSUE THREAD

**Issue by talha0324** [Cezerin2/Server#99]
Cannot use routes in admin app, as pm2 serve does not support the routing.
for reference:
[visit this issue at stackoverflow](https://stackoverflow.com/questions/52077935/how-to-configure-pm2-serve-command-to-serve-multi-page-react-app)

because if you disable the developerMode and then the admin page goes to login as:
http://localhost:3002/login 
it gives error of 404 on this.
@vamcart

**Comment by vamcart** [comment]
You need to use web server for this url.
Check this video - Cezerin installation by docker - https://www.youtube.com/watch?v=xZ0XUrobaMg&t=1s

With docker you don't have this problem, because admin app using web server. nginx.

**Comment by vamcart** [comment]
Connect to our slack chat - https://join.slack.com/t/cezerin2/shared_invite/enQtNTE5NzYxMzA5ODc5LTVkZjM4ODUwMmNlMmMyZTkxYjg5N2QxZmQ5NjA1NTg3OWM2ZjU1NzVmNWM0N2E3ZmJjM2Q3MjQ5OGFmNTBmYjg
